### ISSUE TITLE
Latest version not working in opera

### ISSUE THREAD

**Issue by dmnmsc** [deanoemcke/thegreatsuspender#165]
The previous Great Suspender version was working fine in Opera. But since you updated the extension (with its new look), it's not working anymore. Clicking on "Suspend this tab" does nothing.

There is any chance to fix the extension to make it work in Opera as well? It's a must on my browser.

Thanks.

**Comment by greatsuspender** [comment]
Hi. Could you please confirm the extension version number? I'm pretty sure this was fixed in the most recent version (v6.14). Which has not yet been fully rolled out.
You can always uninstall and reinstall to get this new version - but remember to unsuspend all tabs first.

**Comment by greatsuspender** [comment]
I believe this is the same issues as reported in Issue #162

**Comment by dmnmsc** [comment]
Hi,

Im using v6.14 but still have the problem. Just noticed the suspend option is not working when using the icon, but working fine when using keyboard shortcut (ctrl+shift+s).

**Comment by deanoemcke** [comment]
@dmnmsc have you tried uninstalling and reinstalling? if so, it would be good to get some debug info on what is happening when you click the button from the icon. are you able to open up the background page for the extension (you need to enable developer mode in your extensions) and check to see if there are any errors?

**Comment by dmnmsc** [comment]
Yes, sure, still the same:

I got an "Uncaught TypeError: Cannot read property 'gsUtils' of null" error."  This is the whole output: https://dl.dropboxusercontent.com/u/2135959/greatsuspender.txt

Moreover, the background page's console says: Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED

But this is showing when launching the backround page. Clicking on TheGreatSuspender button offers no output. And I'm not able to see any useful there.

**Comment by deanoemcke** [comment]
did it happen to specify a file and line number of the '..gsUtils of null' error?
would you be able to try installing the latest gitHub version to see if that has the same issues? it will be easier to debug as well.
instructions on installing the gitHub version can be found in the readme of this project.
thanks for you help with this.

**Comment by dmnmsc** [comment]
Still the same behavior installing the git version.

According to info, the error is happening in line 7 of options.html:
options.html --> js/options.js:7 (función anónima)

But I have a new one as well (line 1 in options-html): 
Refused to execute JavaScript URL because it violates the following Co.... available at: https://dl.dropboxusercontent.com/u/2135959/greatsuspenderrefuse.txt
options.html:1 (función anónima)
---------------------------

Just noticed every time I ckick on "suspend this tab button", the session management changes info:

Current session:

1 window, 11 tabs: 24th March 2015resuspendreloadexportsave

Is it saving the history instead of suspending the desired tab?

**Comment by deanoemcke** [comment]
Can you try editing the local background.js file - line 16: change it to debug = true;
Then restart the extension and repeat your tests. Try suspending a tab both with the hotkey, and by clicking the icon.
Then check the background page and copy and paste the exact output you see in the console of the background page.
Sorry to ask for more info, but I wasn't able to diagnose the problem from what you've told me so far.

**Comment by dmnmsc** [comment]
Sure.

I have a lot of info on console, the most  interesting part  is:

Using "Suspend this tab button" is doing:
listener fired: suspendOne
background.js:658 Objectid: "mdhjeklpjjippcaiinlaaabfemcccjdb"url: "chrome-extension://mdhjeklpjjippcaiinlaaabfemcccjdb/popup.html"__proto__: Object

While suspend this tab shortcut (ctrl+shift+s) does:
listener fired: reportTabState
background.js:658 ObjectframeId: 0id: "mdhjeklpjjippcaiinlaaabfemcccjdb"tab: Objecturl: "https://github.com/deanoemcke/thegreatsuspender/issues/165#issuecomment-85236141"__proto__: Object

The button is doing "suspendOne" (which is not working), and shortcut is doing "reportTabState" which works like a charm.

Note, "Suspend other tabs" and "unsuspend other tabs" buttons are working fine.

**Comment by deanoemcke** [comment]
any chance you could copy and paste the entire console output into dropbox like you did earlier? context around these events would be useful.

**Comment by dmnmsc** [comment]
Yes, but there are a lot of items to expand, and its a never ending. Moreover, pasting to a text looks really bad, it's a mess because is not using the same format. 

Anyway, here you have the automated saved info (without expanding all the variables):
What button does: https://dl.dropboxusercontent.com/u/2135959/Button.log
What shortcut does:  https://dl.dropboxusercontent.com/u/2135959/shortcut1.log  and  https://dl.dropboxusercontent.com/u/2135959/shortcut2.log

**Comment by deanoemcke** [comment]
I'm sorry but I'm really not seeing anything odd here. 
I've just committed some optimistic code that might have an effect but can't really tell seeing as I cant recreate the problem at my end.
Try uninstalling and then reinstalling the extension from the latest code on gitHub (from the master branch, not the release tag). It MAY fix your problem. Let me know.

**Comment by dmnmsc** [comment]
Hey, you did it!!

Thank you a lot!! Button and shortcut are working like a charm right now.

BIG THANKS!!

**Comment by deanoemcke** [comment]
That's great news. Thanks heaps for helping me sort it out. I'll try to get the fixed version info the Chrome store shortly.

**Comment by dmnmsc** [comment]
Unfortunately, there is a new issue. When opening opera the suspended tab can't be recovered unless I move back and then forward. I guess it's better to open a new issue:
When opening browser: https://dl.dropboxusercontent.com/u/2135959/nogreatsuspendertab.png
After move back and forward:  https://dl.dropboxusercontent.com/u/2135959/yesgreatsuspendertab1.png

**Comment by deanoemcke** [comment]
@dmnmsc that's weird. it looks like it's not running the javascript when the page is initially loaded. it would be great if you could open this as a new issue. be sure to specify that it's an opera specific bug.

**Comment by deanoemcke** [comment]
@dmnmsc somebody else seems to have a similar issue to yours #173. are you still having problems with this?

**Comment by dmnmsc** [comment]
Hi, just tested again. I'm using your 6.15 version and all is working fine. Said that, I'm testing this with opera-developer (29.0.1795.14). Opera stable's extension never was updated.

Just looked at the issue and yes, it's the same issue I had.
