### ISSUE TITLE
"Unsuspend all tabs" is broken

### ISSUE THREAD

**Issue by paulirish** [deanoemcke/thegreatsuspender#361]
As of recently (last month?), it doesnt work anymore.
1. have some suspended tabs in the chrome window
2. open GS menu
3. hit Unsuspend All Tabs
4. the suspended tabs in that window remain suspended.

**Comment by boyan-sharic** [comment]
It happens to me to.
But it's not 'Unsuspend all tabs', it's 'Realod all tabs'.
![image](https://cloud.githubusercontent.com/assets/10822610/12529556/c947959a-c1bb-11e5-9317-bce7b51f53bb.png)

**Comment by cisso** [comment]
I've noticed the same, and I suspect that changing the delay for tab suspension causes "Unsuspend all tabs" to break.

Setup:
- OS: OS X 10.9.5
- Chrome: 47.0.2526.111
- The Great Suspender: 2.61
- Suspend after: 4 hours
- No OS or Chrome restart for several consecutive days.

Steps:
- 2016-01-25: With approx. 30 tabs suspended in a window, I was able to unsuspend them without problems.
- 2016-01-26: Approx. 40 tabs suspended. Changed delay to 1 day. Immediately afterwards clicking  "Unsuspend all tabs" had no effect.

**Comment by cisso** [comment]
Dug into the background page a bit more (using Chrome's developer mode), and it seems that there are some weird issues with `chrome.windows.getLastFocused` returning the wrong window.

**Comment by boyan-sharic** [comment]
I've just noticed that if I select all suspended tabs (using Shift + Click) and move them from the current Chrome window (thus, creating new Chrome windows) and that press 'Reload all tabs' within TGS - the option actually works.

**Comment by JacobDorman** [comment]
Can confirm ... this button doesn't work as i expect (unsuspend all tabs in this window)

![screen shot 2016-02-04 at 17 00 13](https://cloud.githubusercontent.com/assets/1334947/12807154/d915a422-cb60-11e5-8a9a-22bff9fcdcc9.jpg)

**Comment by boyan-sharic** [comment]
@JacobDorman 
Have you tried my solution?
It really works as a temporary solution until this matter is resolved.

**Comment by deanoemcke** [comment]
@paulirish what version of the extension do you have? and have you continued to encounter this issue or was it a once-off possibly fixed by a chrome restart?

@boyan-sharic from your screenshot you seem to have a very old version of the extension. unfortunately due to the nature of how the extension works, I have had to disable automatic updates of the extension. the only way to update is to perform an uninstall and then reinstall. make sure you unsuspend all tabs before doing this. and also note that you will lose your settings and any save sessions you might have.

for those people have issues with 'unsuspend all tabs' - can you please try performing the operation using the hotkeys (which you can set in from the settings page) instead of the popup menu to see if either one works? If it is the issue referred to by @cisso then the hotkey method should work where the popup method fails.

**Comment by altern8tif** [comment]
@deanoemcke Can confirm that the hotkey works vs trying to unsuspend all tabs via the popup menu.  But restarting Chrome doesn't solve the popup menu bug.

Running the latest version of the extension v6.21.

**Comment by deanoemcke** [comment]
Possibly duplicate of #325

**Comment by deanoemcke** [comment]
Can somebody please confirm whether this is still an issue in the latest release? (v3.60).
Thanks.

**Comment by boyan-sharic** [comment]
I have v6.30 and 'Unsusped all tabs' works as expected.
